---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "appwrite.fullname" $ }}-realtime"
  labels:
{{ include "appwrite.labels" $ | indent 4 }}
    app.kubernetes.io/component: realtime
spec:
  selector:
    matchLabels:
{{ include "appwrite.selectorLabels" $ | indent 6 }}
      app.kubernetes.io/component: realtime
  {{- if not .Values.realtime.autoscaling.enabled }}
  replicas: {{ .Values.realtime.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
{{ include "appwrite.labels" $ | indent 8 }}
        app.kubernetes.io/component: realtime
      annotations:
        checksum/config-env: {{ include (print $.Template.BasePath "/config/env.yaml") . | sha256sum }}
        checksum/secrets-env: {{ include (print $.Template.BasePath "/secrets/env.yaml") . | sha256sum }}
        checksum/secrets-db: {{ include (print $.Template.BasePath "/secrets/db.yaml") . | sha256sum }}
        checksum/secrets-redis: {{ include (print $.Template.BasePath "/secrets/redis.yaml") . | sha256sum }}
    spec:
      initContainers:
      {{- include "redisCheck" $ | nindent 6 }}
      {{- include "dbCheck" $ | nindent 6 }}
      containers:
      - name: appwrite-realtime
        image: "{{ .Values.appwrite.image.repository }}:{{ .Values.appwrite.image.tag | default .Chart.AppVersion }}"
        {{- with .Values.appwrite.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        command:
          - "realtime"
        ports:
        - containerPort: 80
          name: http
        env:
          - name: _APP_WORKER_PER_CORE
            value: {{ .Values.realtime.workerPerCore | quote }}
        envFrom:
        - configMapRef:
            name: {{ include "appwrite.fullname" $ }}-env
        - secretRef:
            name: {{ include "appwrite.fullname" $ }}-env
        - secretRef:
            name: {{ include "appwrite.fullname" $ }}-db-env
        - secretRef:
            name: {{ include "appwrite.fullname" $ }}-redis-env
        resources:
{{ toYaml .Values.realtime.resources | indent 10 }}