dist: xenial

arch:
  - amd64

os: linux

language: shell

notifications:
  email:
  - team@appwrite.io
  
services:
- docker

before_install:
- curl -fsSL https://get.docker.com | sh
- echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
- mkdir -p $HOME/.docker
- echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
- sudo service docker start
- >
  if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
    echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
  fi
- docker --version
- docker buildx create --use
- chmod -R u+x ./.travis-ci

install:
- docker-compose up -d
- sleep 10

jobs:
  include:
    - stage: ps
      script: docker ps
    - stage: logs
      script: docker-compose logs appwrite
    - stage: doctor
      script: docker-compose exec appwrite doctor
    - stage: vars
      script: docker-compose exec appwrite vars
    - stage: tests
      script: docker-compose exec appwrite test /usr/src/code/tests/unit
      script: docker-compose exec appwrite test /usr/src/code/tests/e2e

deploy:
  - provider: script
    edge: true
    script: ./.travis-ci/deploy.sh
    on:
      repo: appwrite/appwrite
      branch: deploy
