{{- if .Values.appwrite.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "appwrite.fullname" $ }}-core
  labels:
{{ include "appwrite.labels" $ | indent 4 }}
{{- if .Values.appwrite.ingress.annotations }}
  annotations:
{{- toYaml .Values.appwrite.ingress.annotations | nindent 4 }}
{{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.appwrite.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "appwrite.fullname" $ }}-core
                port:
                  number: 80
  {{- if .Values.appwrite.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.appwrite.domain }}
      secretName: {{ include "appwrite.fullname" $ }}-tls
  {{- end -}}
{{- end -}}
