---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "appwrite.fullname" $ }}-redis-env"
  labels:
{{ include "appwrite.labels" $ | indent 4 }}
type: Opaque
data:
  {{ if .Values.redis.user -}}_APP_REDIS_USER: {{ .Values.redis.user | b64enc }}{{- end -}}
  {{ if .Values.redis.pass -}}_APP_REDIS_PASS: {{ .Values.redis.pass | b64enc }}{{- end -}}
  _APP_REDIS_HOST:  {{ include "appwrite.fullname" . | printf "%s-redis-master" | b64enc }}
  _APP_REDIS_PORT: {{ "6379" | b64enc }}
