---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "appwrite.fullname" $ }}-core"
  labels:
{{ include "appwrite.labels" $ | indent 4 }}
    app.kubernetes.io/component: core
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
{{ include "appwrite.selectorLabels" $ | indent 4 }}
    app.kubernetes.io/component: core
