---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "appwrite.fullname" $ }}-telegraf"
  labels:
{{ include "appwrite.labels" $ | indent 4 }}
    app.kubernetes.io/component: telegraf
spec:
  ports:
    - port: 8125
      targetPort: 8125
  selector:
{{ include "appwrite.selectorLabels" $ | indent 4 }}
    app.kubernetes.io/component: telegraf
