name: "Benchmark Update Baseline"

on:
  push:
    branches:
      - master

jobs:
  benchmark-update:
    name: Benchmark Update Baseline
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 1

      - name: Build & Run Appwrite
        run:  |
          export COMPOSE_INTERACTIVE_NO_CLI
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1
          export BUILDKIT_PROGRESS=plain
          docker pull composer:2.0
          docker compose build appwrite
          docker compose up -d
          sleep 30

      - name: Doctor
        run: docker compose exec -T appwrite doctor

      - name: Run Benchmark and Update Baseline
        run: |
          rm -rf .phpbench/*
          docker compose exec -T appwrite benchmark --tag=baseline

      - name: Commit updated baseline benchmark
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update benchmark baseline
