
name: "PHPStan"
on: [pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
    - name: Setup PHP
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: swoole
    - name: Install Dependencies
      run: composer install --prefer-dist
    - name: Run PHPStan
      run: vendor/bin/phpstan

