name: "Tests"

on: [pull_request]
jobs:
  tests:
    name: Lint, Test, Benchmark
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Checkout Pull Request HEAD
      run: git checkout HEAD^2

    - name: Install Dependencies
      run: docker run --rm -v $PWD:/app composer install --profile --ignore-platform-reqs

    - name: Run Linter
      run: docker run --rm -v $PWD:/app composer lint

    - name: Build Appwrite
      # Upstream bug causes buildkit pulls to fail so prefetch base images
      # https://github.com/moby/moby/issues/41864
      run:  |
        export COMPOSE_INTERACTIVE_NO_CLI
        export DOCKER_BUILDKIT=1
        export COMPOSE_DOCKER_CLI_BUILD=1
        export BUILDKIT_PROGRESS=plain
        docker pull composer:2.0
        docker compose build appwrite
        docker compose up -d
        sleep 30

    - name: Run Doctor
      run: docker compose exec -T appwrite doctor

    - name: Print Environment Variables
      run:  docker compose exec -T appwrite vars

    - name: Run Tests
      run: docker compose exec -T appwrite test --debug

    - name: Run Benchmark
      continue-on-error: true
      run: docker compose exec -T appwrite benchmark --ref=baseline --progress=plain
